spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/QR_PDF_parser
    username: postgres
    password: 7890
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
